### ISSUE TITLE
`assertFalse(undefined)` behavior 🤔

### ISSUE THREAD

**Issue by treylav** [bfrymire/crispy#48]
Hello.

Crude example first:

```haxe
runner = new TestRunner("Test runner")
suite = new TestSuite("Test suite")
runner.addTestSuite(suite)

test_assert_false_undefined = new TestCase("Assertion to undefined", function(){
	assertFalse(undefined)
	assertIsUndefined(undefined)
	assertTrue(undefined)
})
suite.addTestCase(test_assert_false_undefined)

runner.run()
```

First two assertions are true, last one is false. The fact that the first test passes successfully looks like not a best way for me. 

**I understand that this is standard GML behavior due to its bool and undefined logic.** But I think it's actually harmful: the difference between false and undefined is often that something went wrong during the test. In my opinion, this is a potentially very large field for false-positive cases. 

I understand that the problem is conceptual and, in part, my proposal goes against the ideas of GML, but, in my opinion, the potential harm from the current behavior is much greater. I agree with any solution: return `false` in such a situation, return `undefined` (not sure if this is the best option for assertion expression). Due to the controversial nature of the subject, this issue is an invitation to discussion.

Thank you in advance.

**Comment by bfrymire** [comment]
Hi,

Thanks for bringing this to my attention. Great example for replicating the issue.

You've helped find a bug in how `assertTrue()`/`assertFalse()` are being compared. The expression would first be converted into a boolean to check for a valid comparison. The boolean conversion would then be used for the comparison, which is where the issue lies.

So while `false == undefined` is false; `false == bool(undefined)` is true, which is the issue you're pointing out in your example.
